# Generated by Django 5.2.8 on 2025-11-13 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='users',
            new_name='customer',
        ),
    ]
